# Generated by Django 5.0.3 on 2024-03-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='image',
            new_name='Image',
        ),
    ]
